# Generated by Django 3.0.3 on 2020-02-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_auto_20200209_0702'),
        ('user', '0003_auto_20200209_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='skill.Skill'),
        ),
    ]
