# Generated by Django 3.0.3 on 2020-02-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_auto_20200209_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='sub_skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='_skill_sub_skills_+', to='skill.Skill'),
        ),
    ]
