# Generated by Django 3.0.3 on 2020-02-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_auto_20200209_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='sub_skills',
            field=models.ManyToManyField(blank=True, related_name='parent_skill', to='skill.Skill'),
        ),
    ]
